# Site settings
title: Maison d'hôtes Agadir
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  Appartement à louer avec terrasse à Agadir, Maroc.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
name: Ahmed
twitter_username: leiluspocus
github_username:  leiluspocus
phonenumber: (+212)-624-222723

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


